const UserActionTypes={
    GOOGLE_SIGN_IN_STARTS:'GOOGLE_SIGN_IN_STARTS',
    EMAIL_SIGN_IN_STARTS:'EMAIL_SIGN_IN_STARTS',
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILS:'SIGN_IN_FAILS',
    CHECK_USER_SESSION:'CHECK_USER_SESSION',
    SIGN_OUT_STARTS:'SIGN_OUT_STARTS',
    SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILS:'SIGN_OUT_FAILS',
    SIGN_UP_STARTS:'SIGN_UP_STARTS',
    SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
    SIGN_UP_FAILS:'SIGN_UP_FAILS',
}

export default UserActionTypes